name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05

      - name: Build Node environment via flake
        run: nix develop --accept-flake-config --command node --version

      - name: Install dependencies
        run: nix develop --accept-flake-config --command npm ci

      - name: Run tests
        run: nix develop --accept-flake-config --command npm test